### ISSUE TITLE
PermissionError: [WinError 5] Access is denied:

### ISSUE THREAD

**Issue by roidy** [chadparry/kodi-repository.chad.parry.org#8]
When using this script on a Windows 10 machine I get the following error:-

`PermissionError: [WinError 5] Access is denied: 'C:\\Users\\roidy\\AppData\\Local\\Temp\\tmphoaqvqwo-repo\\.git\\objects\\pack\\pack-381764dcb682846e70c505b21f0aa836bf009b44.idx'`

**Comment by chadparry** [comment]
It's likely that this error happens while the script is cleaning up, after your repository already got created correctly. Do you know whether the repository looks right? To investigate further, I'd like to know what your exact command was, and whether there was any other output from the script.

**Comment by roidy** [comment]
This is my command and output:-

`D:\>create_repository.py --datadir output https://github.com/roidy/skin.singular`

```
Traceback (most recent call last):
  File "D:\create_repository.py", line 410, in <module>
    main()
  File "D:\create_repository.py", line 406, in main
    args.addon, data_path, info_path, checksum_path, args.compressed, args.no_parallel)
  File "D:\create_repository.py", line 338, in create_repository
    raise result.exc_info[1]
WindowsError: [Error 5] Access is denied: 'c:\\users\\roidy\\appdata\\local\\temp\\tmpacqr6g-repo\\.git\\objects\\pack\\pack-381764dcb682846e70c505b21f0aa836bf009b44.idx'
```

I get the following directory and file structure:-

```
output
  |
  +-- skin.singular
           |
           |-- addon.xml
           |-- LICENSE.txt
           |-- skin.singular-0.0.1.zip
           +-- skin.singular-0.0.1.zip.md5
```

But I am missing addons.xml and addons.xml.md5 in the output directory, the script fails before they are created.

This only happen when creating the repository from an online github repo, running the script against a local source directory works perfectly fine.

Thanks for the help.

**Comment by chadparry** [comment]
If you don't mind, I'd like you to test a workaround that I've put together. Please download a copy of the script from here: https://raw.githubusercontent.com/chadparry/kodi-repository.chad.parry.org/windows-8/tools/create_repository.py . Also, if you could add the parameter `--no-parallel` then that will give me additional diagnostic info. Thanks.

**Comment by roidy** [comment]
Thank you, that works perfectly. Although running with `--no-parallel` doesn't give any diagnostic information that I can see. But I can confirm that it is working fine now with no errors and all files are generated.

**Comment by chadparry** [comment]
Good, I've merged the fix into master. The `--no-parallel` option only gives more info during a failure, so that's fine. Thanks.
