### ISSUE TITLE
Wont work with zip files

### ISSUE THREAD

**Issue by roidy** [chadparry/kodi-repository.chad.parry.org#9]
I have a zip file of my addon that contains a single directory like so:-

```
script.gtv.helper.zip -----+
                           |
                           +-- script.gtv.helper (directory)
                                            |
                                            +-- addon.xml
                                            +-- script.py

```
Clearly my zip file only contains one root directory however when I run 

`create_repository.py script.gtv.helper.zip`

I get the following error:-

```
Traceback (most recent call last):
  File "create_repository.py", line 425, in <module>
    main()
  File "create_repository.py", line 420, in main
    create_repository(
  File "create_repository.py", line 353, in create_repository
    raise result.exc_info[1]
  File "create_repository.py", line 296, in fetch_addon
    addon_metadata = fetch_addon_from_zip(
  File "create_repository.py", line 254, in fetch_addon_from_zip
    raise RuntimeError('Archive should contain one directory')
RuntimeError: Archive should contain one directory
```
Running on Window 10 using both python 2.7.18 and 3.8.6 gives the same error. Help please

**Comment by chadparry** [comment]
I tried to reproduce this with a ZIP archive that looked like yours and I didn't get an error. Let's make sure that your ZIP archive has the structure you think it does. Please list the contents of the ZIP and compare it with this:
```
$ unzip -l script.gtv.helper.zip
Archive:  script.gtv.helper.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2021-01-17 13:08   script.gtv.helper/
       47  2021-01-17 13:08   script.gtv.helper/script.py
     1138  2021-01-17 13:06   script.gtv.helper/addon.xml
---------                     -------
     1185                     3 files
```

**Comment by roidy** [comment]
Thanks for the reply, here the exact zip file I'm using for you to look at:- 

[script.gtv.helper.zip](https://github.com/chadparry/kodi-repository.chad.parry.org/files/5828851/script.gtv.helper.zip)

**Comment by chadparry** [comment]
I see something that is likely to be the problem. The paths in ZIP archives are supposed to be separated by the `/` character, but `os.path.sep` is set to `\`. My code assumed that the ZIP archive used the same path separator as the OS.

I've published version 2.3.2 of the script to resolve this. Please give it a try.
```
wget https://raw.githubusercontent.com/chadparry/kodi-repository.chad.parry.org/tools-2.3.2/tools/create_repository.py && chmod +x create_repository.py
```

**Comment by roidy** [comment]
Unfortunately this now seems to add too many separators to the path:-

```
C:\Users\roidy\Documents\GitHub\Source\Make_REPO_Leia>create_repository.py script.gtv.helper.zip
Traceback (most recent call last):
  File "C:\Users\roidy\Documents\GitHub\Source\Make_REPO_Leia\create_repository.py", line 431, in <module>
    main()
  File "C:\Users\roidy\Documents\GitHub\Source\Make_REPO_Leia\create_repository.py", line 427, in main
    args.addon, data_path, info_path, checksum_path, args.compressed, args.no_parallel)
  File "C:\Users\roidy\Documents\GitHub\Source\Make_REPO_Leia\create_repository.py", line 359, in create_repository
    raise result.exc_info[1]
KeyError: "There is no item named 'script.gtv.helper\\\\addon.xml' in the archive"  
```

**Comment by chadparry** [comment]
Sorry, that was my fault. I fixed the first problem but I didn't boot up a Windows machine to check whether there would be other problems. This time I found four other places where the wrong slash was being used. I've verified that your ZIP archive works fine now. You'll find the fixes in version 2.3.3.

**Comment by roidy** [comment]
Big thanks, this now works great using python 3

However one thing to note is that the changes don't work under Python 2.7.18

```
C:\Users\roidy\Documents\GitHub\Source\Make_REPO_Matrix>create_repository.py script.gtv.helper.zip
Traceback (most recent call last):
  File "C:\Users\roidy\Documents\GitHub\Source\Make_REPO_Matrix\create_repository.py", line 428, in <module>
    main()
  File "C:\Users\roidy\Documents\GitHub\Source\Make_REPO_Matrix\create_repository.py", line 424, in main
    args.addon, data_path, info_path, checksum_path, args.compressed, args.no_parallel)
  File "C:\Users\roidy\Documents\GitHub\Source\Make_REPO_Matrix\create_repository.py", line 337, in create_repository
    for addon_location in addon_locations]
  File "C:\Users\roidy\Documents\GitHub\Source\Make_REPO_Matrix\create_repository.py", line 293, in fetch_addon
    addon_location, target_folder)
  File "C:\Users\roidy\Documents\GitHub\Source\Make_REPO_Matrix\create_repository.py", line 276, in fetch_addon_from_zip
    if (not os.path.samefile(addon_source_folder, addon_target_folder) or
AttributeError: 'module' object has no attribute 'samefile'
```

**Comment by chadparry** [comment]
Might as well fix that too. I'm getting lazy about Python 2 since it already sunset, but I haven't officially pulled support. I removed the dependency on `os.path.samefile` although I didn't boot up Windows and install Python 2 to test it. Fingers crossed. :)

Thanks for the feedback.

**Comment by roidy** [comment]
That works perfect in both Python 2 and 3.

Big thanks for fixing this 👍
